apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: ashwin0630/springboot-demo:latest
          ports:
            - containerPort: 8080
